# Generated by Django 4.1.5 on 2023-01-27 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100, verbose_name='Заголовок поста')),
                ('post_text', models.TextField(max_length=1000, verbose_name='Текст поста')),
                ('post_author', models.CharField(max_length=100, verbose_name='Автор поста')),
                ('post_date', models.DateTimeField(auto_now=True, verbose_name='Дата поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('comment_author', models.CharField(max_length=100, verbose_name='Автор комментария')),
                ('comment_date', models.DateTimeField(verbose_name='Дата комментария')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='np_app.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
