# Generated by Django 4.1.5 on 2023-01-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата комментария'),
        ),
    ]
